service: email-service

provider:
  name: aws
  runtime: python3.9
  timeout: 30   # 👈 ADD THIS

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post
plugins:
  - serverless-offline